name: one_context
description: OneContext provides a simple way to deal with Dialogs, Overlays and Navigations with no need of BuildContext.
version: 0.1.1
author: Emanuel Braz - fastencoding@gmail.com
homepage: https://github.com/emanuel-braz/one_context.git

environment:
  sdk: ">=2.1.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter

dev_dependencies:
  flutter_test:
    sdk: flutter
    
flutter:
